config/routes.rb
Rails.application.routes.draw do
  resources :chats

  resources :employees
  resources :project_managers, controller: 'employees', type: 'ProjectManager'
  resources :team_leaders, controller: 'employees', type: 'TeamLeader'
  resources :developers, controller: 'employees', type: 'Developer'
  resources :testers, controller: 'employees', type: 'Tester'

  resources :customers
  resources :orders

  resources :questions

  get '/datatable' => 'orders#datatable'

  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :options
  accepts_nested_attributes_for :options, allow_destroy: true
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
    @question.options.build
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to @question, notice: "Successfully created question."
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to @question, notice: "Successfully updated question."
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_url, notice: "Successfully destroyed question."
  end

  private
    def question_params
      params.require(:question).permit(:title, options_attributes: [:id, :content, :_destroy])
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
  def link_to_add_fields(name, f, association)
    new_object = f.object.send(association).klass.new
    id = new_object.object_id
    fields = f.fields_for(association, new_object, child_index: id) do |builder|
      render(association.to_s.singularize + "_fields", f: builder)
    end
    link_to(name, '#', class: "add_fields", data: {id: id, fields: fields.gsub("\n", "")})
  end
end

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <% if @question.errors.any? %>
    <div class="error_messages">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, :class => "form-control", :placeholder => "Type your question" %>
  </div>
  
  <%= f.fields_for :options do |builder| %>
    <%= render 'option_fields', f: builder %>
  <% end %>

  <div class="form-group">
    <%= link_to_add_fields "Add Option", f, :options %>
  </div>
  
  <div class="form-group">
    <%= f.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/questions/_option_fields.html.erb
<fieldset>
  <%= f.hidden_field :_destroy %>
  <div class="form-group">
    <div class="form-row">
      <div class="col-9">
        <%= f.text_field :content, :class => "form-control", :placeholder => "Option" %>
      </div>
      <div class="col-3">
        <span class="fas fa-trash-alt">
          <%= link_to "Remove", '#', class: "remove_fields" %>
        </span>
      </div>
    </div>
  </div>
</fieldset>

app/views/questions/edit.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', questions_path %>
    </span>
  </p>

  <div class="edit">
    <h3>Edit Question</h3>

    <%= render "form" %>
  </div>
</div>

app/views/questions/index.html.erb
<div class="content">
  <div class="list">
    <h2>Questions</h2>

    <p class="add-new">
      <span class="fas fa-plus-circle"></span> <%= link_to 'New Question', new_question_path %>
    </p>

    <div class="questions">
      <% if @questions.length > 0 %>
        <% @questions.each do |question| %>
          <p class="question">
            <h4><%= link_to question.title, question %></h4>
          </p>
        <% end %>
      <% else %>
        <br><br><p class="text-center">No data available</p>
      <% end %>
    </div>

  </div>
</div>

app/views/questions/new.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', questions_path %>
    </span>
  </p>

  <div class="new">
    <h3>New Question</h3>

    <%= render "form" %>
  </div>
</div>

app/views/questions/show.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', questions_path %>
    </span>
  </p>

  <div class="show">
    <h3><%= @question.title %></h3>

    <ol class="options">
      <% @question.options.each do |option| %>
        <li>
          <%= option.content %>
        </li>
      <% end %>
    </ol>

    <div class="form-group">
      <span class="fas fa-edit">
        <%= link_to 'Edit', edit_question_path(@question) %> |
      </span>

      <span class="fas fa-trash-alt">
        <%= link_to 'Delete', question_path(@question), method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
  </div>
</div>