config/routes.rb
Rails.application.routes.draw do
  resources :chats

  resources :employees
  resources :project_managers, controller: 'employees', type: 'ProjectManager'
  resources :team_leaders, controller: 'employees', type: 'TeamLeader'
  resources :developers, controller: 'employees', type: 'Developer'
  resources :testers, controller: 'employees', type: 'Tester'

  resources :customers
  resources :orders

  resources :questions

  get '/datatable' => 'orders#datatable'

  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/employee.rb
class Employee < ApplicationRecord
  self.inheritance_column = :designation

  validates :designation, presence: true

  scope :projectmanagers, -> { where(designation: 'ProjectManager') }
  scope :teamleaders, -> { where(designation: 'TeamLeader') }
  scope :developers, -> { where(designation: 'Developer') }
  scope :testers, -> { where(designation: 'Tester') }

  def self.responsibilities
		raise 'Abstract Method'
	end

  def self.designations
    %w(ProjectManager TeamLeader Developer Tester)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  before_action :set_designation

  # GET /employees
  def index
    @employees = designation_class.all
    @designation = designation_class
  end

  # GET /employees/:id
  def show
    @response = designation_class.responsibilities
  end

  # GET /employees/new
  def new
    @employee = designation_class.new
  end

  # GET /employees/:id/edit
  def edit
  end

  # POST /employees
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: '#{designation} was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/:id
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: '#{designation} was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/:id
  def destroy
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url, notice: '#{designation} was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_designation
      @designation = designation
    end

    def designation
      Employee.designations.include?(params[:type]) ? params[:type] : "Employee"
    end

    def designation_class
      designation.constantize
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def employee_params
      params.require(designation.underscore.to_sym).permit(:name, :email, :designation)
    end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, :class => "form-control", :placeholder => "Type name" %>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, :class => "form-control", :placeholder => "Type email" %>
  </div>

  <div class="form-group">
    <%= form.label :designation %>
    <%= form.select :designation, Employee.designations.map {|r| [r.humanize, r.camelcase]}, {}, disabled: @designation != "Employee", :class => "form-control" %>
    
    <% if @designation != "Employee" %>
      <%= form.hidden_field :designation, value: @designation %>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', employees_path %>
    </span>
  </p>

  <div class="edit">
    <h3>Editing Employee</h3>

    <%= render 'form', employee: @employee %>
  </div>
</div>

app/views/employees/index.html.erb
<div class="content">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="/employees">Employees</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/project_managers">Project Managers</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/team_leaders">Team Leaders</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/developers">Developers</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/testers">Testers</a>
    </li>
  </ul>

  <div class="list">
    <h2><%= @designation %>s</h2>

    <p class="add-new">
      <span class="fas fa-plus-circle"></span> <%= link_to 'New Employee', new_employee_path %>
    </p>

    <table class="table table-hover">
      <thead class="table-secondary">
        <tr>
          <th>Name</th>
          <th>Email</th>
          <th>Designation</th>
          <th class="text-center" colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% if @employees.length > 0 %>
          <% @employees.each do |employee| %>
            <tr>
              <td><%= employee.name %></td>
              <td><%= employee.email %></td>
              <td><%= employee.designation %></td>
              <td class="text-center"><span class="fas fa-eye"> <%= link_to 'Show', employee %></span></td>
              <td class="text-center"><span class="fas fa-edit"> <%= link_to 'Edit', edit_employee_path(employee) %></span></td>
              <td class="text-center"><span class="fas fa-trash-alt"> <%= link_to 'Delete', employee, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td class="text-center" colspan="6">No data available</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/employees/new.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', employees_path %>
    </span>
  </p>

  <div class="new">
    <h3>New Employee</h3>

    <%= render 'form', employee: @employee %>
  </div>
</div>

app/views/employees/show.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', employees_path %>
    </span>
  </p>

  <div class="show">
    <h3>Show Employee Details</h3>
    <p>
      <strong>Name:</strong>
      <%= @employee.name %>
    </p>

    <p>
      <strong>Email:</strong>
      <%= @employee.email %>
    </p>

    <p>
      <strong>Designation:</strong>
      <%= @employee.designation %>
    </p>

    <p>
      <strong>Responsibilities:</strong>
      <%= @response %>
    </p>

    <div class="form-group">
      <span class="fas fa-edit">
        <%= link_to 'Edit', edit_employee_path(@employee) %> |
      </span>

      <span class="fas fa-trash-alt">
        <%= link_to 'Delete', employee_path(@employee), method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
  </div>
</div>