config/routes.rb
Rails.application.routes.draw do
  resources :chats

  resources :employees
  resources :project_managers, controller: 'employees', type: 'ProjectManager'
  resources :team_leaders, controller: 'employees', type: 'TeamLeader'
  resources :developers, controller: 'employees', type: 'Developer'
  resources :testers, controller: 'employees', type: 'Tester'

  resources :customers
  resources :orders

  resources :questions

  get '/datatable' => 'orders#datatable'

  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/chat.rb
class Chat < ApplicationRecord
end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController
  before_action :set_chat, only: [:show, :edit, :update, :destroy]

  # GET /chats
  def index
    @chats = Chat.all
  end

  # GET /chats/:id
  def show
  end

  # GET /chats/new
  def new
    @chats = Chat.all
    @chat = Chat.new
  end

  # GET /chats/:id/edit
  def edit
  end

  # POST /chats
  def create
    @chat = Chat.new(chat_params)

    respond_to do |format|
      if @chat.save
        ActionCable.server.broadcast 'chat_channel', content: @chat
        # format.html { redirect_to @chat, notice: 'Chat was successfully created.' }
        # format.json { render :show, status: :created, location: @chat }
      else
        format.html { render :new }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chats/:id
  def update
    respond_to do |format|
      if @chat.update(chat_params)
        format.html { redirect_to @chat, notice: 'Chat was successfully updated.' }
        format.json { render :show, status: :ok, location: @chat }
      else
        format.html { render :edit }
        format.json { render json: @chat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chats/:id
  def destroy
    @chat.destroy

    respond_to do |format|
      format.html { redirect_to chats_url, notice: 'Chat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chat
      @chat = Chat.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def chat_params
      params.require(:chat).permit(:message)
    end
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/views/chats/_form.html.erb
<%= form_with(model: chat, remote: true) do |form| %>
  <% if chat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(chat.errors.count, "error") %> prohibited this chat from being saved:</h2>

      <ul>
        <% chat.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :message %>
    <%= form.text_field :message, :class => "form-control", :placeholder => "Type name" %>
  </div>

  <div class="form-group">
    <%= form.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/chats/edit.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', chats_path %>
    </span>
  </p>

  <div class="new">
    <h3>Editing Customer</h3>

    <%= render 'form', chat: @chat %>
  </div>
</div>

app/views/chats/index.html.erb
<div class="content">
  <div class="list">
    <h2>Chats</h2>

    <p class="add-new">
      <span class="fas fa-plus-circle"></span> <%= link_to 'New Chat', new_chat_path %>
    </p>

    <table class="table table-hover">
      <thead class="table-secondary">
        <tr>
          <th>Message</th>
          <th class="text-center" colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% if @chats.length > 0 %>
          <% @chats.each do |chat| %>
            <tr>
              <td><%= chat.message %></td>
              <td class="text-center"><span class="fas fa-eye"> <%= link_to 'Show', chat %></span></td>
              <td class="text-center"><span class="fas fa-edit"> <%= link_to 'Edit', edit_chat_path(chat) %></span></td>
              <td class="text-center"><span class="fas fa-trash-alt"> <%= link_to 'Delete', chat, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
            </tr>
          <% end %>
        <% else %>
          <tr>
            <td class="text-center" colspan="4">No data available</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/chats/new.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', chats_path %>
    </span>
  </p>

  <div class="new">
    <h3>New Chat</h3>

    <%# @chats.each do |chat| %>
      <p><%#= chat.message %></p>
    <%# end %>
    
    <div id="new_message"%></div>

    <%= render 'form', chat: @chat %>
  </div>
</div>

app/views/chats/show.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', chats_path %>
    </span>
  </p>

  <div class="show">
    <h3>Show Customer Details</h3>
    <p>
      <strong>Message:</strong>
      <%= @chat.message %>
    </p>

    <div class="form-group">
      <span class="fas fa-edit">
        <%= link_to 'Edit', edit_chat_path(@chat) %> |
      </span>

      <span class="fas fa-trash-alt">
        <%= link_to 'Delete', chat_path(@chat), method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
  </div>
</div>