config/routes.rb
Rails.application.routes.draw do
  resources :chats

  resources :employees
  resources :project_managers, controller: 'employees', type: 'ProjectManager'
  resources :team_leaders, controller: 'employees', type: 'TeamLeader'
  resources :developers, controller: 'employees', type: 'Developer'
  resources :testers, controller: 'employees', type: 'Tester'

  resources :customers
  resources :orders

  resources :questions

  get '/datatable' => 'orders#datatable'

  root 'welcome#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    @orders = Order.all
    @customers = Customer.all

    respond_to do |format|
      format.html
      format.json { render json: OrderDatatable.new(params) }
    end
  end

  # GET /orders/:id
  def show
    @order = Order.find(params[:id])
    @customer = Customer.find(@order.customer_id)
  end

  # GET /orders/new
  def new
    @order = Order.new
    @customers = Customer.all
  end

  # GET /orders/:id/edit
  def edit
    @customers = Customer.all
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/:id
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/:id
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:order_id, :item_name, :price, :customer_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :item_name %>
    <%= form.text_field :item_name, :class => "form-control", :placeholder => "Type item name" %>
  </div>

  <div class="form-group">
    <%= form.label :order_id %>
    <%= form.text_field :order_id, :class => "form-control", :placeholder => "Type order id" %>
  </div>

  <div class="form-group">
    <%= form.label :price %>
    <%= form.text_field :price, :class => "form-control", :placeholder => "Type price" %>
  </div>

  <div class="form-group">
    <label for="order_customer_id">Select a customer</label>
    <%= form.collection_select :customer_id, @customers, :id, :name, prompt: true, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit :class => "btn btn-success" %>
  </div>
<% end %>

app/views/orders/datatable.html.erb
<div class="content">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="/customers">Customers</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/orders">Orders</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/datatable">Datatable</a>
    </li>
  </ul>

  <div class="list">
    <h2>Orders</h2>

    <table class="table table-hover row-border" id="orders-datatable" data-source="<%= orders_path(format: :json) %>">
      <thead class="table-secondary">
        <tr>
          <th>Order ID</th>
          <th>Item Name</th>
          <th>Price</th>
          <th>Customer</th>
        </tr>
      </thead>
  
      <tbody>
      </tbody>
    </table>
  </div>
</div>

<script>
  jQuery(document).ready(function() {
    $('#orders-datatable').dataTable({
      "processing": true,
      "serverSide": true,
      "ajax": $('#orders-datatable').data('source'),
      "pagingType": "full_numbers",
      "columns": [
        {"data": "order_id"},
        {"data": "item_name"},
        {"data": "price"},
        {"data": "customer_name"}
      ]
    });
  });
</script>

app/views/orders/edit.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', orders_path %>
    </span>
  </p>

  <div class="new">
    <h3>Editing Order</h3>

    <%= render 'form', order: @order %>
  </div>
</div>

app/views/orders/index.html.erb
<div class="content">
  <ul class="nav nav-tabs">
    <li class="nav-item">
      <a class="nav-link" href="/customers">Customers</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/orders">Orders</a>
    </li>
    <li class="nav-item">
      <a class="nav-link" href="/datatable">Datatable</a>
    </li>
  </ul>

  <div class="list">
    <h2>Orders</h2>

    <p class="add-new">
      <span class="fas fa-plus-circle"></span> <%= link_to 'New Order', new_order_path %>
    </p>

    <table class="table table-hover">
      <thead class="table-secondary">
        <tr>
          <th>Order ID</th>
          <th>Item Name</th>
          <th>Price</th>
          <th>Customer</th>
          <th class="text-center" colspan="3">Actions</th>
        </tr>
      </thead>

      <tbody>
        <% if @orders.length > 0 %>
          <% @orders.each do |order| %>
            <% @customers.each do |customer| %>
              <% if(order.customer_id == customer.id) %>
                <tr>
                  <td><%= order.order_id %></td>
                  <td><%= order.item_name %></td>
                  <td><%= order.price %></td>
                  <td><%= link_to customer.name, customer_path(customer) %></td>
                  <td class="text-center"><span class="fas fa-eye"> <%= link_to 'Show', order %></span></td>
                  <td class="text-center"><span class="fas fa-edit"> <%= link_to 'Edit', edit_order_path(order) %></span></td>
                  <td class="text-center"><span class="fas fa-trash-alt"> <%= link_to 'Delete', order, method: :delete, data: { confirm: 'Are you sure?' } %></span></td>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        <% else %>
          <tr>
            <td class="text-center" colspan="7">No data available</td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/new.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', orders_path %>
    </span>
  </p>

  <div class="new">
    <h3>New order</h3>

    <%= render 'form', order: @order %>
  </div>
</div>

app/views/orders/show.html.erb
<div class="content">
  <p class="back">
    <span class="fas fa-arrow-circle-left">
      <%= link_to 'Back', orders_path %>
    </span>
  </p>

  <div class="show">
    <h3>Show Order Details</h3>
    <p>
      <strong>Order ID:</strong>
      <%= @order.order_id %>
    </p>

    <p>
      <strong>Item Name:</strong>
      <%= @order.item_name %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= @order.price %>
    </p>

    <p>
      <strong>Customer:</strong>
      <%= link_to @customer.name, customer_path(@customer) %>
    </p>

    <div class="form-group">
      <span class="fas fa-edit">
        <%= link_to 'Edit', edit_order_path(@order) %> |
      </span>

      <span class="fas fa-trash-alt">
        <%= link_to 'Delete', order_path(@order), method: :delete, data: { confirm: 'Are you sure?' } %>
      </span>
    </div>
  </div>
</div>